export const WS_PATH = {
  ROOM: "/ws/room",
} as const;

export const WS_ROOM = {
  JOIN: "room:join" as const,
  MUTE_PARTICIPANT: "room:mute_participant" as const,
  UNMUTE_PARTICIPANT: "room:unmute_participant" as const,
  BLOCK_CAMERA: "room:block_camera" as const,
  UNBLOCK_CAMERA: "room:unblock_camera" as const,
  BLOCK_SCREENSHARE: "room:block_screenshare" as const,
  UNBLOCK_SCREENSHARE: "room:unblock_screenshare" as const,
  YOU_MUTED: "room:you_muted" as const,
  YOU_UNMUTED: "room:you_unmuted" as const,
  YOU_CAMERA_BLOCKED: "room:you_camera_blocked" as const,
  YOU_CAMERA_UNBLOCKED: "room:you_camera_unblocked" as const,
  YOU_SCREENSHARE_BLOCKED: "room:you_screenshare_blocked" as const,
  YOU_SCREENSHARE_UNBLOCKED: "room:you_screenshare_unblocked" as const,
  PARTICIPANT_MUTED: "room:participant_muted" as const,
  PARTICIPANT_UNMUTED: "room:participant_unmuted" as const,
  PARTICIPANT_CAMERA_BLOCKED: "room:participant_camera_blocked" as const,
  PARTICIPANT_CAMERA_UNBLOCKED: "room:participant_camera_unblocked" as const,
  PARTICIPANT_SCREENSHARE_BLOCKED: "room:participant_screenshare_blocked" as const,
  PARTICIPANT_SCREENSHARE_UNBLOCKED: "room:participant_screenshare_unblocked" as const,
  MUTED_PARTICIPANTS: "room:muted_participants" as const,
  CAMERA_BLOCKED_PARTICIPANTS: "room:camera_blocked_participants" as const,
  SCREENSHARE_BLOCKED_PARTICIPANTS: "room:screenshare_blocked_participants" as const,
  STREAM_STARTED: "room:stream_started" as const,
  STREAM_STOPPED: "room:stream_stopped" as const,
  ROLE_UPDATED: "room:role_updated" as const,
  ROOM_UPDATED: "room:updated" as const,
  TAKEN_OVER: "room:taken_over" as const,
  KICKED: "room:kicked" as const,
  BANNED: "room:banned" as const,
  DELETED: "room:deleted" as const,
};
